/*
 * Copyright (c) 2026, Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

#include "val_rmm.h"

enum test_intent {
    RD_UNALIGNED = 0X0,
    RD_OUTSIDE_OF_PERMITTED_PA = 0X1,
    RD_DEV_MEM_MMIO = 0X2,
    RD_GRAN_STATE_UNDELEGATED = 0X3,
    REC_UNALIGNED = 0X4,
    REC_OUTSIDE_OF_PERMITTED_PA = 0X5,
    REC_DEV_MEM_MMIO = 0X6,
    REC_GRAN_STATE_UNDELEGATED = 0X7,
    REC_OWNER = 0X8,
    PDEV_UNALIGNED = 0X9,
    PDEV_OUTSIDE_OF_PERMITTED_PA = 0XA,
    PDEV_DEV_MEM_MMIO = 0XB,
    PDEV_GRAN_STATE_UNDELEGATED = 0XC,
    VDEV_UNALIGNED = 0XD,
    VDEV_OUTSIDE_OF_PERMITTED_PA = 0XE,
    VDEV_DEV_MEM_MMIO = 0XF,
    VDEV_GRAN_STATE_UNDELEGATED = 0X10,
    VDEV_PDEV = 0X11,
    SIZE_INVALID = 0X12,
    BASE_BOUND = 0X13,
    TOP_BOUND = 0X14,
    TOP_GRAN_ALIGN = 0X15,
};

struct stimulus {
    char msg[100];
    uint64_t abi;
    enum test_intent label;
    uint64_t status;
    uint64_t index;
};

static struct stimulus test_data[] = {
    {.msg = "rd_align",
    .abi = RMI_VDEV_VALIDATE_MAPPING,
    .label = RD_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_bound",
    .abi = RMI_VDEV_VALIDATE_MAPPING,
    .label = RD_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_bound",
    .abi = RMI_VDEV_VALIDATE_MAPPING,
    .label = RD_DEV_MEM_MMIO,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_VDEV_VALIDATE_MAPPING,
    .label = RD_GRAN_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rec_align",
    .abi = RMI_VDEV_VALIDATE_MAPPING,
    .label = REC_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rec_bound",
    .abi = RMI_VDEV_VALIDATE_MAPPING,
    .label = REC_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rec_bound",
    .abi = RMI_VDEV_VALIDATE_MAPPING,
    .label = REC_DEV_MEM_MMIO,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rec_gran_state",
    .abi = RMI_VDEV_VALIDATE_MAPPING,
    .label = REC_GRAN_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "owner",
    .abi = RMI_VDEV_VALIDATE_MAPPING,
    .label = REC_OWNER,
    .status = RMI_ERROR_REC,
    .index = 0},
    // {.msg = "pdev_align",
    // .abi = RMI_VDEV_VALIDATE_MAPPING,
    // .label = PDEV_UNALIGNED,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "pdev_bound",
    // .abi = RMI_VDEV_VALIDATE_MAPPING,
    // .label = PDEV_OUTSIDE_OF_PERMITTED_PA,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "pdev_bound",
    // .abi = RMI_VDEV_VALIDATE_MAPPING,
    // .label = PDEV_DEV_MEM_MMIO,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "pdev_state",
    // .abi = RMI_VDEV_VALIDATE_MAPPING,
    // .label = PDEV_GRAN_STATE_UNDELEGATED,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "vdev_align",
    // .abi = RMI_VDEV_VALIDATE_MAPPING,
    // .label = VDEV_UNALIGNED,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "vdev_bound",
    // .abi = RMI_VDEV_VALIDATE_MAPPING,
    // .label = VDEV_OUTSIDE_OF_PERMITTED_PA,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "vdev_bound",
    // .abi = RMI_VDEV_VALIDATE_MAPPING,
    // .label = VDEV_DEV_MEM_MMIO,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "vdev_state",
    // .abi = RMI_VDEV_VALIDATE_MAPPING,
    // .label = VDEV_GRAN_STATE_UNDELEGATED,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "vdev_pdev",
    // .abi = RMI_VDEV_VALIDATE_MAPPING,
    // .label = VDEV_PDEV,
    // .status = RMI_ERROR_DEVICE,
    // .index = 0},
    {.msg = "size_valid",
    .abi = RMI_VDEV_VALIDATE_MAPPING,
    .label = SIZE_INVALID,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "base_bound",
    .abi = RMI_VDEV_VALIDATE_MAPPING,
    .label = BASE_BOUND,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "top_bound",
    .abi = RMI_VDEV_VALIDATE_MAPPING,
    .label = TOP_BOUND,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "top_align",
    .abi = RMI_VDEV_VALIDATE_MAPPING,
    .label = TOP_GRAN_ALIGN,
    .status = RMI_ERROR_INPUT,
    .index = 0}
};
