/*
 * Copyright (c) 2026, Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

#include "val_rmm.h"

enum test_intent {
    PDEV_UNALIGNED = 0x0,
    PDEV_OUTSIDE_OF_PERMITTED_PA = 0x1,
    PDEV_DEV_MEM_MMIO = 0x2,
    PDEV_GRAN_STATE_UNDELEGATED = 0x3,
    PARAMS_UNALIGNED = 0x4,
    PARAMS_PAS_REALM = 0x5,
    PARAMS_PAS_SECURE = 0x6,
    DEVICE_ID_INVALID = 0x7,
    DEVICE_ID_NOT_USED = 0x8,
    ROOT_PORT_ID_INVALID = 0x9,
    RID_RANGE_INVALID = 0xA,
    OVERLAPPED_RID_RANGE = 0xB,
    BASE_ADDRESS_RANGE_UNALIGNED = 0xC,
    TOP_ADDRESS_RANGE_UNALIGNED = 0xD,
    ADDR_RANGES_OUTSIDE_PERMITTED_MEMORY = 0xE,
    ADDR_RANGES_OVERLAP_WITHIN_PDEV = 0xF,
    ADDR_RANGES_OVERLAP_OTHER_PDEV = 0x10,
    NUM_AUX_INVALID = 0x11,
    AUX_UNALIGNED = 0x12,
    AUX_ALIASED = 0x13,
    AUX_STATE_UNDELEGATED = 0x14,
    NCOH_IDE_SID_OUTSIDE_BOUND = 0x15
};

struct stimulus {
    char msg[100];
    uint64_t abi;
    enum test_intent label;
    uint64_t status;
    uint64_t index;
};

static struct stimulus test_data[] = {
    {.msg = "pdev_align",
    .abi = RMI_PDEV_CREATE,
    .label = PDEV_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "pdev_bound",
    .abi = RMI_PDEV_CREATE,
    .label = PDEV_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "pdev_bound",
    .abi = RMI_PDEV_CREATE,
    .label = PDEV_DEV_MEM_MMIO,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "pdev_state",
    .abi = RMI_PDEV_CREATE,
    .label = PDEV_GRAN_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "params_align",
    .abi = RMI_PDEV_CREATE,
    .label = PARAMS_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "params_pas",
    .abi = RMI_PDEV_CREATE,
    .label = PARAMS_PAS_REALM,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "params_pas",
    .abi = RMI_PDEV_CREATE,
    .label = PARAMS_PAS_SECURE,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    // {.msg = "params_valid",
    // .abi = RMI_PDEV_CREATE,
    // .label = DEVICE_ID_INVALID,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "params_valid",
    // .abi = RMI_PDEV_CREATE,
    // .label = DEVICE_ID_NOT_USED,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "params_valid",
    // .abi = RMI_PDEV_CREATE,
    // .label = ROOT_PORT_ID_INVALID,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "params_valid",
    // .abi = RMI_PDEV_CREATE,
    // .label = RID_RANGE_INVALID,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "params_valid",
    // .abi = RMI_PDEV_CREATE,
    // .label = OVERLAPPED_RID_RANGE,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "params_valid",
    // .abi = RMI_PDEV_CREATE,
    // .label = BASE_ADDRESS_RANGE_UNALIGNED,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "params_valid",
    // .abi = RMI_PDEV_CREATE,
    // .label = TOP_ADDRESS_RANGE_UNALIGNED,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "params_valid",
    // .abi = RMI_PDEV_CREATE,
    // .label = ADDR_RANGES_OUTSIDE_PERMITTED_MEMORY,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "params_valid",
    // .abi = RMI_PDEV_CREATE,
    // .label = ADDR_RANGES_OVERLAP_WITHIN_PDEV,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "params_valid",
    // .abi = RMI_PDEV_CREATE,
    // .label = ADDR_RANGES_OVERLAP_OTHER_PDEV,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    {.msg = "num_aux",
    .abi = RMI_PDEV_CREATE,
    .label = NUM_AUX_INVALID,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "aux_align",
    .abi = RMI_PDEV_CREATE,
    .label = AUX_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "aux_alias",
    .abi = RMI_PDEV_CREATE,
    .label = AUX_ALIASED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "aux_state",
    .abi = RMI_PDEV_CREATE,
    .label = AUX_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "ncoh_ide_sid_bound",
    .abi = RMI_PDEV_CREATE,
    .label = NCOH_IDE_SID_OUTSIDE_BOUND,
    .status = RMI_ERROR_INPUT,
    .index = 0}
};
