/*
 * Copyright (c) 2026, Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

#include "val_rmm.h"

enum test_intent {
    RD_UNALIGNED = 0X0,
    RD_OUTSIDE_OF_PERMITTED_PA = 0X1,
    RD_DEV_MEM_MMIO = 0X2,
    RD_GRAN_STATE_UNDELEGATED = 0X3,
    PDEV_UNALIGNED = 0X4,
    PDEV_OUTSIDE_OF_PERMITTED_PA = 0X5,
    PDEV_DEV_MEM_MMIO = 0X6,
    PDEV_GRAN_STATE_UNDELEGATED = 0X7,
    VDEV_UNALIGNED = 0X8,
    VDEV_OUTSIDE_OF_PERMITTED_PA = 0X9,
    VDEV_DEV_MEM_MMIO = 0XA,
    VDEV_GRAN_STATE_UNDELEGATED = 0XB,
    INVALID_RD = 0XD,
    INVALID_PDEV = 0XE,
    PARAMS_UNALIGNED = 0XF,
    PARAMS_PAS_REALM = 0x10,
    PARAMS_PAS_SECURE = 0x11,
    VDEV_GRAN_STATE_UNDELEGATED_INVALID_PDEV = 0X12
};

struct stimulus {
    char msg[100];
    uint64_t abi;
    enum test_intent label;
    uint64_t status;
    uint64_t index;
};

static struct stimulus test_data[] = {
    {.msg = "rd_align",
    .abi = RMI_VDEV_GET_MEASUREMENTS,
    .label = RD_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_bound",
    .abi = RMI_VDEV_GET_MEASUREMENTS,
    .label = RD_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_bound",
    .abi = RMI_VDEV_GET_MEASUREMENTS,
    .label = RD_DEV_MEM_MMIO,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_gran_state",
    .abi = RMI_VDEV_GET_MEASUREMENTS,
    .label = RD_GRAN_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "pdev_align",
    .abi = RMI_VDEV_GET_MEASUREMENTS,
    .label = PDEV_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "pdev_bound",
    .abi = RMI_VDEV_GET_MEASUREMENTS,
    .label = PDEV_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "pdev_bound",
    .abi = RMI_VDEV_GET_MEASUREMENTS,
    .label = PDEV_DEV_MEM_MMIO,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "pdev_gran_state",
    .abi = RMI_VDEV_GET_MEASUREMENTS,
    .label = PDEV_GRAN_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "vdev_align",
    .abi = RMI_VDEV_GET_MEASUREMENTS,
    .label = VDEV_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "vdev_bound",
    .abi = RMI_VDEV_GET_MEASUREMENTS,
    .label = VDEV_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "vdev_bound",
    .abi = RMI_VDEV_GET_MEASUREMENTS,
    .label = VDEV_DEV_MEM_MMIO,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "vdev_gran_state",
    .abi = RMI_VDEV_GET_MEASUREMENTS,
    .label = VDEV_GRAN_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    /* TODO: Uncomment once TF-RMM fix the issue */
    // {.msg = "vdev_realm",
    // .abi = RMI_VDEV_GET_MEASUREMENTS,
    // .label = INVALID_RD,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    {.msg = "vdev_pdev",
    .abi = RMI_VDEV_GET_MEASUREMENTS,
    .label = INVALID_PDEV,
    .status = RMI_ERROR_DEVICE,
    .index = 0},
    {.msg = "params_align",
    .abi = RMI_VDEV_GET_MEASUREMENTS,
    .label = PARAMS_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "params_align",
    .abi = RMI_VDEV_GET_MEASUREMENTS,
    .label = PARAMS_PAS_REALM,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "params_align",
    .abi = RMI_VDEV_GET_MEASUREMENTS,
    .label = PARAMS_PAS_SECURE,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "vdev_gran_state_vdev_pdev",
    .abi = RMI_VDEV_GET_MEASUREMENTS,
    .label = VDEV_GRAN_STATE_UNDELEGATED_INVALID_PDEV,
    .status = RMI_ERROR_INPUT,
    .index = 0},
};
