/*
 * Copyright (c) 2026, Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

#include "val_rmm.h"

enum test_intent {
    RD_UNALIGNED = 0X0,
    RD_OUTSIDE_OF_PERMITTED_PA = 0X1,
    RD_DEV_MEM_MMIO = 0X2,
    RD_GRAN_STATE_UNDELEGATED = 0X3,
    PDEV_UNALIGNED = 0X4,
    PDEV_OUTSIDE_OF_PERMITTED_PA = 0X5,
    PDEV_DEV_MEM_MMIO = 0X6,
    PDEV_GRAN_STATE_UNDELEGATED = 0X7,
    PDEV_STATE_NEW = 0x8,
    PDEV_CATEGORY_CMEM_CXL = 0X9,
    VDEV_UNALIGNED = 0XA,
    VDEV_OUTSIDE_OF_PERMITTED_PA = 0XB,
    VDEV_DEV_MEM_MMIO = 0XC,
    VDEV_GRAN_STATE_UNDELEGATED = 0XD,
    PARAMS_UNALIGNED = 0XE,
    PARAMS_PAS_REALM = 0XF,
    PARAMS_PAS_SECURE = 0X10,
    DA_FEATURE_FALSE = 0X11,
    NUM_AUX_INVALID = 0X12,
    AUX_UNALIGNED = 0X13,
    AUX_ALIASED = 0X14,
    AUX_STATE_UNDELEGATED = 0X15,
    VDEV_ID_USED = 0X16,
    TDI_ID_USED = 0X17,
    TDI_ID_NOT_IN_RANGE = 0X18
};

struct stimulus {
    char msg[100];
    uint64_t abi;
    enum test_intent label;
    uint64_t status;
    uint64_t index;
};

static struct stimulus test_data[] = {
    {.msg = "rd_align",
    .abi = RMI_VDEV_CREATE,
    .label = RD_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_bound",
    .abi = RMI_VDEV_CREATE,
    .label = RD_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_bound",
    .abi = RMI_VDEV_CREATE,
    .label = RD_DEV_MEM_MMIO,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_gran_state",
    .abi = RMI_VDEV_CREATE,
    .label = RD_GRAN_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "pdev_align",
    .abi = RMI_VDEV_CREATE,
    .label = PDEV_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "pdev_bound",
    .abi = RMI_VDEV_CREATE,
    .label = PDEV_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "pdev_bound",
    .abi = RMI_VDEV_CREATE,
    .label = PDEV_DEV_MEM_MMIO,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "pdev_gran_state",
    .abi = RMI_VDEV_CREATE,
    .label = PDEV_GRAN_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "pdev_state",
    .abi = RMI_VDEV_CREATE,
    .label = PDEV_STATE_NEW,
    .status = RMI_ERROR_DEVICE,
    .index = 0},
    /* TODO: Uncomment once TF-RMM fix the issue */
    // {.msg = "pdev_category",
    // .abi = RMI_VDEV_CREATE,
    // .label = PDEV_CATEGORY_CMEM_CXL,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    {.msg = "vdev_align",
    .abi = RMI_VDEV_CREATE,
    .label = VDEV_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "vdev_bound",
    .abi = RMI_VDEV_CREATE,
    .label = VDEV_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "vdev_bound",
    .abi = RMI_VDEV_CREATE,
    .label = VDEV_DEV_MEM_MMIO,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "vdev_gran_state",
    .abi = RMI_VDEV_CREATE,
    .label = VDEV_GRAN_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "params_align",
    .abi = RMI_VDEV_CREATE,
    .label = PARAMS_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "params_pas",
    .abi = RMI_VDEV_CREATE,
    .label = PARAMS_PAS_REALM,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "params_pas",
    .abi = RMI_VDEV_CREATE,
    .label = PARAMS_PAS_SECURE,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "da_en",
    .abi = RMI_VDEV_CREATE,
    .label = DA_FEATURE_FALSE,
    .status = RMI_ERROR_REALM,
    .index = 0},
    {.msg = "num_aux",
    .abi = RMI_VDEV_CREATE,
    .label = NUM_AUX_INVALID,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    // {.msg = "aux_align",
    // .abi = RMI_VDEV_CREATE,
    // .label = AUX_UNALIGNED,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "aux_alias",
    // .abi = RMI_VDEV_CREATE,
    // .label = AUX_ALIASED,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "aux_state",
    // .abi = RMI_VDEV_CREATE,
    // .label = AUX_STATE_UNDELEGATED,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "vdev_id_free",
    // .abi = RMI_VDEV_CREATE,
    // .label = VDEV_ID_USED,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "tdi_id_free",
    // .abi = RMI_VDEV_CREATE,
    // .label = TDI_ID_USED,
    // .status = RMI_ERROR_INPUT,
    // .index = 0},
    // {.msg = "tdi_id_bound",
    // .abi = RMI_VDEV_CREATE,
    // .label = TDI_ID_NOT_IN_RANGE,
    // .status = RMI_ERROR_INPUT,
    // .index = 0}
};
