/*
 * Copyright (c) 2026, Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

#include "val_rmm.h"

enum test_intent {
    ADDR_UNALIGNED = 0X0,
    ADDR_OUTSIDE_OF_PERMITTED_PA = 0X1,
    ADDR_DEV_MEM_MMIO = 0X2,
    ADDR_GRAN_STATE_UNDELEGATED = 0X3,
    RD_UNALIGNED = 0X4,
    RD_OUTSIDE_OF_PERMITTED_PA = 0X5,
    RD_DEV_MEM_MMIO = 0X6,
    RD_GRAN_STATE_UNDELEGATED = 0X7,
    VDEV_UNALIGNED = 0X8,
    VDEV_OUTSIDE_OF_PERMITTED_PA = 0X9,
    VDEV_DEV_MEM_MMIO = 0XA,
    VDEV_GRAN_STATE_UNDELEGATED = 0XB,
    INVALID_RD = 0XC,
    LEVEL_LT_2 = 0XD,
    LEVEL_OOB = 0XE,
    IPA_UNALIGNED = 0XF,
    IPA_UNPROTECTED = 0X10,
    RTT_WALK = 0X11,
    RTTE_STATE = 0X12,
    RTTE_RIPAS = 0X13
};

struct stimulus {
    char msg[100];
    uint64_t abi;
    enum test_intent label;
    uint64_t status;
    uint64_t index;
};

static struct stimulus test_data[] = {
    {.msg = "addr_align",
    .abi = RMI_VDEV_MAP,
    .label = ADDR_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "addr_bound",
    .abi = RMI_VDEV_MAP,
    .label = ADDR_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "addr_bound",
    .abi = RMI_VDEV_MAP,
    .label = ADDR_DEV_MEM_MMIO,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "addr_state",
    .abi = RMI_VDEV_MAP,
    .label = ADDR_GRAN_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_align",
    .abi = RMI_VDEV_MAP,
    .label = RD_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_bound",
    .abi = RMI_VDEV_MAP,
    .label = RD_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_bound",
    .abi = RMI_VDEV_MAP,
    .label = RD_DEV_MEM_MMIO,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_VDEV_MAP,
    .label = RD_GRAN_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "vdev_align",
    .abi = RMI_VDEV_MAP,
    .label = VDEV_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "vdev_bound",
    .abi = RMI_VDEV_MAP,
    .label = VDEV_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "vdev_bound",
    .abi = RMI_VDEV_MAP,
    .label = VDEV_DEV_MEM_MMIO,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "vdev_gran_state",
    .abi = RMI_VDEV_MAP,
    .label = VDEV_GRAN_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "vdev_realm",
    .abi = RMI_VDEV_MAP,
    .label = INVALID_RD,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "level_bound",
    .abi = RMI_VDEV_MAP,
    .label = LEVEL_LT_2,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "level_bound",
    .abi = RMI_VDEV_MAP,
    .label = LEVEL_OOB,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "ipa_align",
    .abi = RMI_VDEV_MAP,
    .label = IPA_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "ipa_bound",
    .abi = RMI_VDEV_MAP,
    .label = IPA_UNPROTECTED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rtt_walk",
    .abi = RMI_VDEV_MAP,
    .label = RTT_WALK,
    .status = RMI_ERROR_RTT,
    .index = 2},
    {.msg = "rtte_state",
    .abi = RMI_VDEV_MAP,
    .label = RTTE_STATE,
    .status = RMI_ERROR_RTT,
    .index = 3},
    {.msg = "rtte_ripas",
    .abi = RMI_VDEV_MAP,
    .label = RTTE_RIPAS,
    .status = RMI_ERROR_RTT,
    .index = 3}
};
