/*
 * Copyright (c) 2024, Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

#include "val_rmm.h"

enum test_intent {
    RD_UNALIGNED = 0X0,
    RD_DEV_MEM_MMIO = 0X1,
    RD_OUTSIDE_OF_PERMITTED_PA = 0X2,
    RD_STATE_UNDELEGATED = 0X3,
    RD_STATE_DELEGATED = 0X4,
    RD_STATE_REC = 0X5,
    RD_STATE_RTT = 0X6,
    RD_STATE_DATA = 0X7,
    IPA_UNALIGNED = 0X8,
    IPA_UNPROTECTED = 0X9,
    IPA_OUTSIDE_OF_PERMITTED_IPA = 0XA,
    REALM_SINGLE_RTT_TREE = 0XB,
    INDEX_PRIMARY_RTT_TREE = 0XC,
    INDEX_OUT_OF_BOUND = 0XD,
    PRI_STATE_UNASSIGNED = 0XE,
    PRI_STATE_ASSIGNED_EMPTY = 0XF,
    PRI_STATE_DESTROYED = 0X10,
    AUX_STATE_DESTROYED = 0X11,
    AUX_RTT_UNMAPPED = 0X12,
    INDEX_OOB_PRI_STATE_UNASSIGNED = 0X13
};

struct stimulus {
    char msg[100];
    uint64_t abi;
    enum test_intent label;
    uint64_t status;
    uint64_t index;
};

static struct stimulus test_data[] = {
    {.msg = "rd_align",
    .abi = RMI_RTT_AUX_MAP_PROTECTED,
    .label = RD_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_bound",
    .abi = RMI_RTT_AUX_MAP_PROTECTED,
    .label = RD_DEV_MEM_MMIO,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_bound",
    .abi = RMI_RTT_AUX_MAP_PROTECTED,
    .label = RD_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_RTT_AUX_MAP_PROTECTED,
    .label = RD_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_RTT_AUX_MAP_PROTECTED,
    .label = RD_STATE_DELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_RTT_AUX_MAP_PROTECTED,
    .label = RD_STATE_REC,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_RTT_AUX_MAP_PROTECTED,
    .label = RD_STATE_RTT,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_RTT_AUX_MAP_PROTECTED,
    .label = RD_STATE_DATA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "ipa_align",
    .abi = RMI_RTT_AUX_MAP_PROTECTED,
    .label = IPA_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "ipa_bound",
    .abi = RMI_RTT_AUX_MAP_PROTECTED,
    .label = IPA_UNPROTECTED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "ipa_bound",
    .abi = RMI_RTT_AUX_MAP_PROTECTED,
    .label = IPA_OUTSIDE_OF_PERMITTED_IPA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "index_bound",
    .abi = RMI_RTT_AUX_MAP_PROTECTED,
    .label = REALM_SINGLE_RTT_TREE,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "index_bound",
    .abi = RMI_RTT_AUX_MAP_PROTECTED,
    .label = INDEX_PRIMARY_RTT_TREE,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "index_bound",
    .abi = RMI_RTT_AUX_MAP_PROTECTED,
    .label = INDEX_OUT_OF_BOUND,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "pri_state",
    .abi = RMI_RTT_AUX_MAP_PROTECTED,
    .label = PRI_STATE_UNASSIGNED,
    .status = RMI_ERROR_RTT,
    .index = 3},
    {.msg = "pri_state",
    .abi = RMI_RTT_AUX_MAP_PROTECTED,
    .label = PRI_STATE_ASSIGNED_EMPTY,
    .status = RMI_ERROR_RTT,
    .index = 3},
    {.msg = "pri_state",
    .abi = RMI_RTT_AUX_MAP_PROTECTED,
    .label = PRI_STATE_DESTROYED,
    .status = RMI_ERROR_RTT,
    .index = 3},
    {.msg = "aux_destroyed",
    .abi = RMI_RTT_AUX_MAP_PROTECTED,
    .label = AUX_STATE_DESTROYED,
    .status = RMI_ERROR_RTT_AUX,
    .index = 2},
    {.msg = "level",
    .abi = RMI_RTT_AUX_MAP_PROTECTED,
    .label = AUX_RTT_UNMAPPED,
    .status = RMI_ERROR_RTT_AUX,
    .index = 2},
    {.msg = "index_bound_compare_pri_state",
    .abi = RMI_RTT_AUX_MAP_PROTECTED,
    .label = INDEX_OOB_PRI_STATE_UNASSIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0}
};
