/*
 * Copyright (c) 2026, Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

#include "val_rmm.h"

enum test_intent {
    RD_UNALIGNED = 0X0,
    RD_OUTSIDE_OF_PERMITTED_PA = 0X1,
    RD_DEV_MEM_MMIO = 0X2,
    RD_GRAN_STATE_UNDELEGATED = 0X3,
    PDEV_UNALIGNED = 0X4,
    PDEV_OUTSIDE_OF_PERMITTED_PA = 0X5,
    PDEV_DEV_MEM_MMIO = 0X6,
    PDEV_GRAN_STATE_UNDELEGATED = 0X7,
    VDEV_UNALIGNED = 0X8,
    VDEV_OUTSIDE_OF_PERMITTED_PA = 0X9,
    VDEV_DEV_MEM_MMIO = 0XA,
    VDEV_GRAN_STATE_UNDELEGATED = 0XB,
    INVALID_RD = 0XC,
    DATA_UNALIGNED = 0XD,
    DATA_PAS_REALM = 0XE,
    DATA_PAS_SECURE = 0XF,
    REQ_UNALIGNED = 0X10,
    REQ_PAS_REALM = 0X11,
    REQ_PAS_SECURE = 0X12,
    RESP_UNALIGNED = 0X13,
    RESP_PAS_REALM = 0X14,
    RESP_PAS_SECURE = 0X15,
    INVALID_RESP_LEN = 0X16,
    INVALID_PDEV = 0X17,
    VDEV_GRAN_STATE_UNDELEGATED_INVALID_PDEV = 0x18
};

struct stimulus {
    char msg[100];
    uint64_t abi;
    enum test_intent label;
    uint64_t status;
    uint64_t index;
};

static struct stimulus test_data[] = {
    {.msg = "rd_align",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = RD_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_bound",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = RD_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_bound",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = RD_DEV_MEM_MMIO,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_gran_state",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = RD_GRAN_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "pdev_align",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = PDEV_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "pdev_bound",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = PDEV_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "pdev_bound",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = PDEV_DEV_MEM_MMIO,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "pdev_gran_state",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = PDEV_GRAN_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "vdev_align",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = VDEV_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "vdev_bound",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = VDEV_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "vdev_bound",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = VDEV_DEV_MEM_MMIO,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "vdev_gran_state",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = VDEV_GRAN_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "data_align",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = DATA_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "data_pas",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = DATA_PAS_REALM,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "data_pas",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = DATA_PAS_SECURE,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "req_align",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = REQ_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "req_pas",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = REQ_PAS_REALM,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "req_pas",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = REQ_PAS_SECURE,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "resp_align",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = RESP_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "resp_pas",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = RESP_PAS_REALM,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "resp_pas",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = RESP_PAS_SECURE,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "resp_len",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = INVALID_RESP_LEN,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "vdev_pdev",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = INVALID_PDEV,
    .status = RMI_ERROR_DEVICE,
    .index = 0},
    {.msg = "vdev_gran_state_vdev_pdev",
    .abi = RMI_VDEV_COMMUNICATE,
    .label = VDEV_GRAN_STATE_UNDELEGATED_INVALID_PDEV,
    .status = RMI_ERROR_INPUT,
    .index = 0}
};
