/*
 * Copyright (c) 2023, Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

#include "val_rmm.h"

enum test_intent {
    RD_UNALIGNED = 0X0,
    RD_OUTSIDE_OF_PERMITTED_PA = 0X1,
    RD_DEV_MEM = 0X2,
    RD_STATE_UNDELEGATED = 0X3,
    RD_STATE_DELEGATED = 0X4,
    RD_STATE_REC = 0X5,
    RD_STATE_RTT = 0X6,
    RD_STATE_DATA = 0X7,
    REC_UNALIGNED = 0X8,
    REC_OUTSIDE_OF_PERMITTED_PA = 0X9,
    REC_DEV_MEM = 0XA,
    REC_GRAN_STATE_UNDELEGATED = 0XB,
    REC_GRAN_STATE_DELEGATED = 0XC,
    REC_GRAN_STATE_RD = 0XD,
    REC_GRAN_STATE_RTT = 0XE,
    REc_GRAN_STATE_DATA = 0XF,
    REC_OTHER_OWNER = 0X10,
    INVALID_SIZE = 0X11,
    BASE_MISMATCH = 0X12,
    TOP_OUT_OF_BOUND = 0X13,
    BASE_UNALIGNED = 0X14,
    TOP_UNALIGNED = 0X15,
    BASE_MISMATCH_BASE_UNALIGNED = 0X16
};

struct stimulus {
    char msg[100];
    uint64_t abi;
    enum test_intent label;
    uint64_t status;
    uint64_t index;
};

static struct stimulus test_data[] = {
    {.msg = "rd_align",
    .abi = RMI_RTT_SET_RIPAS,
    .label = RD_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_bound",
    .abi = RMI_RTT_SET_RIPAS,
    .label = RD_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_bound",
    .abi = RMI_RTT_SET_RIPAS,
    .label = RD_DEV_MEM,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_RTT_SET_RIPAS,
    .label = RD_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_RTT_SET_RIPAS,
    .label = RD_STATE_DELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_RTT_SET_RIPAS,
    .label = RD_STATE_REC,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_RTT_SET_RIPAS,
    .label = RD_STATE_RTT,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_RTT_SET_RIPAS,
    .label = RD_STATE_DATA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rec_align",
    .abi = RMI_RTT_SET_RIPAS,
    .label = REC_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rec_bound",
    .abi = RMI_RTT_SET_RIPAS,
    .label = REC_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rec_bound",
    .abi = RMI_RTT_SET_RIPAS,
    .label = REC_DEV_MEM,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rec_gran_state",
    .abi = RMI_RTT_SET_RIPAS,
    .label = REC_GRAN_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rec_gran_state",
    .abi = RMI_RTT_SET_RIPAS,
    .label = REC_GRAN_STATE_DELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rec_gran_state",
    .abi = RMI_RTT_SET_RIPAS,
    .label = REC_GRAN_STATE_RD,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rec_gran_state",
    .abi = RMI_RTT_SET_RIPAS,
    .label = REC_GRAN_STATE_RTT,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rec_gran_state",
    .abi = RMI_RTT_SET_RIPAS,
    .label = REc_GRAN_STATE_DATA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rec_owner",
    .abi = RMI_RTT_SET_RIPAS,
    .label = REC_OTHER_OWNER,
    .status = RMI_ERROR_REC,
    .index = 0},
    {.msg = "size_valid",
    .abi = RMI_RTT_SET_RIPAS,
    .label = INVALID_SIZE,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "base_bound",
    .abi = RMI_RTT_SET_RIPAS,
    .label = BASE_MISMATCH,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "top_bound",
    .abi = RMI_RTT_SET_RIPAS,
    .label = TOP_OUT_OF_BOUND,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "base_align",
    .abi = RMI_RTT_SET_RIPAS,
    .label = BASE_UNALIGNED,
    .status = RMI_ERROR_RTT,
    .index = 2},
    {.msg = "top_align",
    .abi = RMI_RTT_SET_RIPAS,
    .label = TOP_UNALIGNED,
    .status = RMI_ERROR_RTT,
    .index = 3},
    {.msg = "base_bound_compare_base_align",
    .abi = RMI_RTT_SET_RIPAS,
    .label = BASE_MISMATCH_BASE_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0}
};
