/*
 * Copyright (c) 2023, Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

#include "val_rmm.h"

enum test_intent {
    PARAMS_UNALIGNED = 0X0,
    PARAMS_DEV_MEM = 0X1,
    PARAMS_OUTSIDE_OF_PERMITTED_PA = 0X2,
    PARAMS_PAS_REALM = 0X3,
    PARAMS_PAS_SECURE = 0X4,
    HASH_ALGO_INVALID = 0X5,
    S2SZ_INVALID = 0X6,
    HASH_ALGO_UNSUPPORTED = 0X7,
    PMU_UNSUPPORTED = 0X8,
    SVE_UNSUPPORTED = 0X9,
    LPA2_UNSUPPORTED = 0XA,
    BPS_UNSUPPORTED = 0XB,
    WPS_UNSUPPORTED = 0XC,
    RTT_BASE_RD_ALIASED = 0XD,
    RD_UNALIGNED = 0XE,
    RD_DEV_MEM = 0XF,
    RD_OUTSIDE_OF_PERMITTED_PA = 0X10,
    RD_STATE_UNDELEGATED = 0X11,
    RD_STATE_RD = 0X12,
    RD_STATE_REC = 0X13,
    RD_STATE_RTT = 0X14,
    RD_STATE_DATA = 0X15,
    RTT_UNALIGNED = 0X16,
    RTT_START_INVALID = 0X17,
    RTT_BASE_UNDELEGATED = 0X18,
    VMID_INVALID = 0X19,
    VMID_USED = 0X1A
};

struct stimulus {
    char msg[100];
    uint64_t abi;
    enum test_intent label;
    uint64_t status;
    uint64_t index;
};

static struct stimulus test_data[] = {
    {.msg = "params_align",
    .abi = RMI_REALM_CREATE,
    .label = PARAMS_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "params_bound",
    .abi = RMI_REALM_CREATE,
    .label = PARAMS_DEV_MEM,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "params_bound",
    .abi = RMI_REALM_CREATE,
    .label = PARAMS_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "params_pas",
    .abi = RMI_REALM_CREATE,
    .label = PARAMS_PAS_REALM,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "params_pas",
    .abi = RMI_REALM_CREATE,
    .label = PARAMS_PAS_SECURE,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "params_valid",
    .abi = RMI_REALM_CREATE,
    .label = HASH_ALGO_INVALID,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "params_valid",
    .abi = RMI_REALM_CREATE,
    .label = S2SZ_INVALID,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "params_supp",
    .abi = RMI_REALM_CREATE,
    .label = HASH_ALGO_UNSUPPORTED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "params_supp",
    .abi = RMI_REALM_CREATE,
    .label = PMU_UNSUPPORTED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "params_supp",
    .abi = RMI_REALM_CREATE,
    .label = SVE_UNSUPPORTED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "params_supp",
    .abi = RMI_REALM_CREATE,
    .label = LPA2_UNSUPPORTED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "params_supp",
    .abi = RMI_REALM_CREATE,
    .label = BPS_UNSUPPORTED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "params_supp",
    .abi = RMI_REALM_CREATE,
    .label = WPS_UNSUPPORTED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "alias",
    .abi = RMI_REALM_CREATE,
    .label = RTT_BASE_RD_ALIASED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_align",
    .abi = RMI_REALM_CREATE,
    .label = RD_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_bound",
    .abi = RMI_REALM_CREATE,
    .label = RD_DEV_MEM,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_bound",
    .abi = RMI_REALM_CREATE,
    .label = RD_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_REALM_CREATE,
    .label = RD_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_REALM_CREATE,
    .label = RD_STATE_RD,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_REALM_CREATE,
    .label = RD_STATE_REC,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_REALM_CREATE,
    .label = RD_STATE_RTT,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_REALM_CREATE,
    .label = RD_STATE_DATA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rtt_align",
    .abi = RMI_REALM_CREATE,
    .label = RTT_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rtt_num_level",
    .abi = RMI_REALM_CREATE,
    .label = RTT_START_INVALID,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rtt_state",
    .abi = RMI_REALM_CREATE,
    .label = RTT_BASE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "vmid_valid",
    .abi = RMI_REALM_CREATE,
    .label = VMID_INVALID,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "vmid_valid",
    .abi = RMI_REALM_CREATE,
    .label = VMID_USED,
    .status = RMI_ERROR_INPUT,
    .index = 0}
};
