/*
 * Copyright (c) 2023, Arm Limited or its affiliates. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

#include "val_rmm.h"

enum test_intent {
    DATA_UNALIGNED = 0X0,
    DATA_DEV_MEM_MMIO = 0X1,
    DATA_OUTSIDE_OF_PERMITTED_PA = 0X2,
    DATA_STATE_UNDELEGATED = 0X3,
    DATA_STATE_RD = 0X4,
    DATA_STATE_REC = 0X5,
    DATA_STATE_RTT = 0X6,
    DATA_STATE_DATA = 0X7,
    RD_UNALIGNED = 0X8,
    RD_DEV_MEM_MMIO = 0X9,
    RD_OUTSIDE_OF_PERMITTED_PA = 0XA,
    RD_STATE_UNDELEGATED = 0XB,
    RD_STATE_DELEGATED = 0XC,
    RD_STATE_REC = 0XD,
    RD_STATE_RTT = 0XE,
    RD_STATE_DATA = 0XF,
    IPA_UNALIGNED = 0X10,
    IPA_UNPROTECTED = 0X11,
    IPA_OUTSIDE_OF_PERMITTED_IPA = 0X12,
    IPA_NOT_MAPPED = 0X13,
    RTTE_STATE_ASSIGNED = 0X14,
    IPA_UNPROTECTED_NOT_MAPPED = 0X16,
    IPA_UNPROTECTED_RTTE_ASSIGNED = 0X17
};

struct stimulus {
    char msg[100];
    uint64_t abi;
    enum test_intent label;
    uint64_t status;
    uint64_t index;
};

static struct stimulus test_data[] = {
    {.msg = "data_align",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = DATA_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "data_bound",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = DATA_DEV_MEM_MMIO,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "data_bound",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = DATA_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "data_state",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = DATA_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "data_state",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = DATA_STATE_RD,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "data_state",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = DATA_STATE_REC,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "data_state",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = DATA_STATE_RTT,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "data_state",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = DATA_STATE_DATA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_align",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = RD_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_bound",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = RD_DEV_MEM_MMIO,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_bound",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = RD_OUTSIDE_OF_PERMITTED_PA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = RD_STATE_UNDELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = RD_STATE_DELEGATED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = RD_STATE_REC,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = RD_STATE_RTT,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rd_state",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = RD_STATE_DATA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "ipa_align",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = IPA_UNALIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "ipa_bound",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = IPA_UNPROTECTED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "ipa_bound",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = IPA_OUTSIDE_OF_PERMITTED_IPA,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "rtt_walk",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = IPA_NOT_MAPPED,
    .status = RMI_ERROR_RTT,
    .index = 2},
    {.msg = "rtte_state",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = RTTE_STATE_ASSIGNED,
    .status = RMI_ERROR_RTT,
    .index = 3},
    {.msg = "ipa_bound_compare_rtt_walk",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = IPA_UNPROTECTED_NOT_MAPPED,
    .status = RMI_ERROR_INPUT,
    .index = 0},
    {.msg = "ipa_bound_compare_rtte_state",
    .abi = RMI_DATA_CREATE_UNKNOWN,
    .label = IPA_UNPROTECTED_RTTE_ASSIGNED,
    .status = RMI_ERROR_INPUT,
    .index = 0}
};
